# Data Quality Checks

## Customers Quality Checks

In [42]:
import pandas as pd

In [43]:
#cutomers table
df=pd.read_csv(r'D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\Data\customers.csv')
df.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,extraction_timestamp,data_source
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127,2026-04-01 21:38:58.421075,DataLake
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008,2026-04-01 21:38:58.421075,DataLake
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278,2026-04-01 21:38:58.421075,DataLake
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553,2026-04-01 21:38:58.421075,DataLake
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820,2026-04-01 21:38:58.421075,DataLake

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           1445 non-null   int64
 1   first_name            1445 non-null   str
 2   last_name             1445 non-null   str
 3   phone                 178 non-null    str
 4   email                 1445 non-null   str
 5   street                1445 non-null   str
 6   city                  1445 non-null   str
 7   state                 1445 non-null   str
 8   zip_code              1445 non-null   int64
 9   extraction_timestamp  1445 non-null   str
 10  data_source           1445 non-null   str
dtypes: int64(2), str(9)
memory usage: 124.3 KB

In [45]:
#● Null Checks: Identify and handle null values in essential fields
def Nulls_Checks(df):
    return df.isnull().sum()/len(df)*100



def Replace_nulls(df,col):

    if df[col].dtype == 'str' :
      df[col]=df[col].fillna('Unknown')

    elif df[col].dtype in ['int64','float64']:
        df[col]=df[col].fillna(0)

    elif df[col].dtype == 'datetime64[ns]':
        df[col]=df[col].fillna(pd.Timestamp.today())

    return df

In [46]:
Nulls_Checks(df)

customer_id              0.000000
first_name               0.000000
last_name                0.000000
phone                   87.681661
email                    0.000000
street                   0.000000
city                     0.000000
state                    0.000000
zip_code                 0.000000
extraction_timestamp     0.000000
data_source              0.000000
dtype: float64

In [47]:
Replace_nulls(df,'phone')

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,extraction_timestamp,data_source
0,1,Debra,Burks,Unknown,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127,2026-04-01 21:38:58.421075,DataLake
1,2,Kasha,Todd,Unknown,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008,2026-04-01 21:38:58.421075,DataLake
2,3,Tameka,Fisher,Unknown,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278,2026-04-01 21:38:58.421075,DataLake
3,4,Daryl,Spence,Unknown,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553,2026-04-01 21:38:58.421075,DataLake
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820,2026-04-01 21:38:58.421075,DataLake
...,...,...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,Unknown,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301,2026-04-01 21:38:58.421075,DataLake
1441,1442,Cassie,Cline,Unknown,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201,2026-04-01 21:38:58.421075,DataLake
1442,1443,Lezlie,Lamb,Unknown,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722,2026-04-01 21:38:58.421075,DataLake
1443,1444,Ivette,Estes,Unknown,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424,2026-04-01 21:38:58.421075,DataLake
1444,1445,Ester,Acevedo,Unknown,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580,2026-04-01 21:38:58.421075,DataLake

In [48]:
Nulls_Checks(df)

customer_id             0.0
first_name              0.0
last_name               0.0
phone                   0.0
email                   0.0
street                  0.0
city                    0.0
state                   0.0
zip_code                0.0
extraction_timestamp    0.0
data_source             0.0
dtype: float64

In [49]:
#● Duplicate Checks: Detect and remove duplicate rows.
def duplicate_checks(df):
    total           = len(df)
    duplicate_count = df.duplicated().sum()
    duplicate_pct   = duplicate_count / total * 100

    print(f"Total Rows       : {total}")
    print(f"Duplicate Rows   : {duplicate_count}")
    print(f"Duplicate %      : {duplicate_pct.round(2)}%")

    if duplicate_count > 0:
        return df[df.duplicated(keep=False)]  # return the duplicate rows
    else:
        print("No duplicates found!")
        return None

duplicate_checks(df)

Total Rows       : 1445
Duplicate Rows   : 0
Duplicate %      : 0.0%
No duplicates found!

In [50]:
import os 
OUTPUT_DIR = r"D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\staging_1"
os.makedirs(OUTPUT_DIR, exist_ok=True)
df.to_csv(os.path.join(OUTPUT_DIR,'customers.csv') , index=False)

## Order_items Quality Checks

In [51]:
df=pd.read_csv(r'D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\Data\order_items.csv')
df.head()

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,data_source
0,1,1,20,1,599.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server
1,1,2,8,2,1799.99,0.07,2026-04-01 01:59:18.974759,PostgreSQl Server
2,1,3,10,2,1549.00,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
3,1,4,16,2,599.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
4,1,5,4,1,2899.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4764 entries, 0 to 4763
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              4764 non-null   int64
 1   item_id               4764 non-null   int64
 2   product_id            4764 non-null   int64
 3   quantity              4764 non-null   int64
 4   list_price            4764 non-null   float64
 5   discount              4764 non-null   float64
 6   extraction_timestamp  4764 non-null   str
 7   data_source           4764 non-null   str
dtypes: float64(2), int64(4), str(2)
memory usage: 297.9 KB

In [53]:
Nulls_Checks(df)

order_id                0.0
item_id                 0.0
product_id              0.0
quantity                0.0
list_price              0.0
discount                0.0
extraction_timestamp    0.0
data_source             0.0
dtype: float64

In [54]:
duplicate_checks(df)

Total Rows       : 4764
Duplicate Rows   : 38
Duplicate %      : 0.8%

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,data_source
6,2,2,16,2,599.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
7,3,1,3,1,999.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
11,2,2,16,2,599.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
12,3,1,3,1,999.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
19,6,5,9,2,2999.99,0.07,2026-04-01 01:59:18.974759,PostgreSQl Server
...,...,...,...,...,...,...,...,...
4750,1614,1,124,1,1499.00,0.07,2026-04-01 01:59:18.974759,PostgreSQl Server
4760,1612,2,289,2,319.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
4761,1612,3,101,2,339.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server
4762,1612,4,293,2,319.99,0.07,2026-04-01 01:59:18.974759,PostgreSQl Server
4763,1612,5,60,1,1559.99,0.10,2026-04-01 01:59:18.974759,PostgreSQl Server

In [55]:
# Maybe a customer_id appears twice — even if other columns differ
def duplicate_checks_Column(df, col=None):
    total = len(df)

    if col:
        duplicate_count = df.duplicated(subset=[col]).sum()
        print(f"Duplicates in '{col}': {duplicate_count} ({duplicate_count/total*100:.2f}%)")
    else:
        duplicate_count = df.duplicated().sum()
        print(f"Full Row Duplicates : {duplicate_count} ({duplicate_count/total*100:.2f}%)")

    if duplicate_count > 0:
        return df[df.duplicated(subset=[col] if col else None, keep=False)]
    else:
        print("No duplicates found!")
        return None

In [58]:
duplicate_checks_Column(df,'order_id')
#its normal to have duplicates in order_id

Duplicates in 'order_id': 3149 (66.10%)

,order_id,item_id,product_id,quantity,list_price,discount,extraction_timestamp,data_source
0,1,1,20,1,599.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server
1,1,2,8,2,1799.99,0.07,2026-04-01 01:59:18.974759,PostgreSQl Server
2,1,3,10,2,1549.00,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
3,1,4,16,2,599.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
4,1,5,4,1,2899.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server
...,...,...,...,...,...,...,...,...
4759,1615,9,182,1,2499.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server
4760,1612,2,289,2,319.99,0.05,2026-04-01 01:59:18.974759,PostgreSQl Server
4761,1612,3,101,2,339.99,0.20,2026-04-01 01:59:18.974759,PostgreSQl Server
4762,1612,4,293,2,319.99,0.07,2026-04-01 01:59:18.974759,PostgreSQl Server
4763,1612,5,60,1,1559.99,0.10,2026-04-01 01:59:18.974759,PostgreSQl Server

In [59]:
#some validations 
# الخصم المفروض يكون بين 0 و 1 بس (0% → 100%)
def validate_discount(df):
    invalid = df[(df['discount'] < 0) | (df['discount'] > 1)]
    print(f"Invalid discounts: {len(invalid)} rows")
    return invalid

validate_discount(df)

Invalid discounts: 0 rows

Empty DataFrame
Columns: [order_id, item_id, product_id, quantity, list_price, discount, extraction_timestamp, data_source]
Index: []

In [60]:
OUTPUT_DIR = r"D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\staging_1"
os.makedirs(OUTPUT_DIR, exist_ok=True)
df.to_csv(os.path.join(OUTPUT_DIR,'order_items.csv') , index=False)

## orders Quality Checks

In [68]:
df=pd.read_csv(r'D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\Data\orders.csv')
df.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id,extraction_timestamp,data_source
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2,2026-04-01 01:59:19.049783,PostgreSQl Server
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6,2026-04-01 01:59:19.049783,PostgreSQl Server
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7,2026-04-01 01:59:19.049783,PostgreSQl Server
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3,2026-04-01 01:59:19.049783,PostgreSQl Server
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6,2026-04-01 01:59:19.049783,PostgreSQl Server

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              1445 non-null   int64
 1   customer_id           1445 non-null   int64
 2   order_status          1445 non-null   int64
 3   order_date            1445 non-null   str
 4   required_date         1445 non-null   str
 5   shipped_date          1445 non-null   str
 6   store_id              1445 non-null   int64
 7   staff_id              1445 non-null   int64
 8   extraction_timestamp  1445 non-null   str
 9   data_source           1445 non-null   str
dtypes: int64(5), str(5)
memory usage: 113.0 KB

In [70]:
Nulls_Checks(df)

order_id                0.0
customer_id             0.0
order_status            0.0
order_date              0.0
required_date           0.0
shipped_date            0.0
store_id                0.0
staff_id                0.0
extraction_timestamp    0.0
data_source             0.0
dtype: float64

In [71]:
duplicate_checks(df)

Total Rows       : 1445
Duplicate Rows   : 0
Duplicate %      : 0.0%
No duplicates found!

In [74]:
duplicate_checks_Column(df,'order_id')

Duplicates in 'order_id': 0 (0.00%)
No duplicates found!

In [75]:
# validations  for order_date required_date shipped_date
#change the data type to datetime
df['order_date']=pd.to_datetime(df['order_date'])
df['required_date']=pd.to_datetime(df['required_date'])
df['shipped_date']=pd.to_datetime(df['shipped_date'])
#check if the data is correct
print(df['order_date'].dtype)
print(df['required_date'].dtype)
print(df['shipped_date'].dtype)

datetime64[us]
datetime64[us]
datetime64[us]

In [76]:
def validate_date(df):
    #order_date must be before required_date
    invalid=df[df['order_date']>df['required_date']]
    print(f"Invalid order_date: {len(invalid)} rows")
    return invalid

validate_date(df)

Invalid order_date: 0 rows

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id, extraction_timestamp, data_source]
Index: []

In [77]:
OUTPUT_DIR = r"D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\staging_1"
os.makedirs(OUTPUT_DIR, exist_ok=True)
df.to_csv(os.path.join(OUTPUT_DIR,'orders.csv') , index=False)

## Products Quality Checks

In [78]:
df=pd.read_csv(r'D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\Data\products.csv')
df.head()

,product_id,product_name,brand_name,category_name,model_year,list_price,extraction_timestamp,data_source
0,1,Trek 820 - 2016,Trek,Mountain Bikes,2016,379.99,2026-04-01 21:38:58.421075,DataLake
1,2,Ritchey Timberwolf Frameset - 2016,Ritchey,Mountain Bikes,2016,749.99,2026-04-01 21:38:58.421075,DataLake
2,3,Surly Wednesday Frameset - 2016,Surly,Mountain Bikes,2016,999.99,2026-04-01 21:38:58.421075,DataLake
3,4,Trek Fuel EX 8 29 - 2016,Trek,Mountain Bikes,2016,2899.99,2026-04-01 21:38:58.421075,DataLake
4,5,Heller Shagamaw Frame - 2016,Heller,Mountain Bikes,2016,1320.99,2026-04-01 21:38:58.421075,DataLake

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            334 non-null    int64
 1   product_name          334 non-null    str
 2   brand_name            334 non-null    str
 3   category_name         334 non-null    str
 4   model_year            334 non-null    int64
 5   list_price            334 non-null    float64
 6   extraction_timestamp  334 non-null    str
 7   data_source           334 non-null    str
dtypes: float64(1), int64(2), str(5)
memory usage: 21.0 KB

In [80]:
Nulls_Checks(df)

product_id              0.0
product_name            0.0
brand_name              0.0
category_name           0.0
model_year              0.0
list_price              0.0
extraction_timestamp    0.0
data_source             0.0
dtype: float64

In [81]:
duplicate_checks(df)

Total Rows       : 334
Duplicate Rows   : 13
Duplicate %      : 3.89%

,product_id,product_name,brand_name,category_name,model_year,list_price,extraction_timestamp,data_source
11,12,Electra Townie Original 21D - 2016,Electra,Cruisers Bicycles,2016,549.99,2026-04-01 21:38:58.421075,DataLake
12,13,Electra Cruiser 1 (24-Inch) - 2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
13,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
15,12,Electra Townie Original 21D - 2016,Electra,Cruisers Bicycles,2016,549.99,2026-04-01 21:38:58.421075,DataLake
16,13,Electra Cruiser 1 (24-Inch) - 2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
17,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
94,92,Haro Shredder 20 - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
95,93,Haro Shredder 20 Girls - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
96,94,Haro Shredder Pro 20 - 2017,Haro,Children Bicycles,2017,249.99,2026-04-01 21:38:58.421075,DataLake
102,92,Haro Shredder 20 - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
103,93,Haro Shredder 20 Girls - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
104,94,Haro Shredder Pro 20 - 2017,Haro,Children Bicycles,2017,249.99,2026-04-01 21:38:58.421075,DataLake
193,188,Trek XM700+ Lowstep - 2018,Trek,Electric Bikes,2018,3499.99,2026-04-01 21:38:58.421075,DataLake
194,189,Trek Lift+ Lowstep - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
195,190,Trek Dual Sport+ - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
197,188,Trek XM700+ Lowstep - 2018,Trek,Electric Bikes,2018,3499.99,2026-04-01 21:38:58.421075,DataLake
198,189,Trek Lift+ Lowstep - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
199,190,Trek Dual Sport+ - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
299,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
300,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake
301,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
302,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake
303,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
304,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake
305,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
306,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake

In [82]:
duplicate_checks_Column(df,'product_id')

Duplicates in 'product_id': 13 (3.89%)

,product_id,product_name,brand_name,category_name,model_year,list_price,extraction_timestamp,data_source
11,12,Electra Townie Original 21D - 2016,Electra,Cruisers Bicycles,2016,549.99,2026-04-01 21:38:58.421075,DataLake
12,13,Electra Cruiser 1 (24-Inch) - 2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
13,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
15,12,Electra Townie Original 21D - 2016,Electra,Cruisers Bicycles,2016,549.99,2026-04-01 21:38:58.421075,DataLake
16,13,Electra Cruiser 1 (24-Inch) - 2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
17,14,Electra Girl's Hawaii 1 (16-inch) - 2015/2016,Electra,Cruisers Bicycles,2016,269.99,2026-04-01 21:38:58.421075,DataLake
94,92,Haro Shredder 20 - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
95,93,Haro Shredder 20 Girls - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
96,94,Haro Shredder Pro 20 - 2017,Haro,Children Bicycles,2017,249.99,2026-04-01 21:38:58.421075,DataLake
102,92,Haro Shredder 20 - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
103,93,Haro Shredder 20 Girls - 2017,Haro,Children Bicycles,2017,209.99,2026-04-01 21:38:58.421075,DataLake
104,94,Haro Shredder Pro 20 - 2017,Haro,Children Bicycles,2017,249.99,2026-04-01 21:38:58.421075,DataLake
193,188,Trek XM700+ Lowstep - 2018,Trek,Electric Bikes,2018,3499.99,2026-04-01 21:38:58.421075,DataLake
194,189,Trek Lift+ Lowstep - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
195,190,Trek Dual Sport+ - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
197,188,Trek XM700+ Lowstep - 2018,Trek,Electric Bikes,2018,3499.99,2026-04-01 21:38:58.421075,DataLake
198,189,Trek Lift+ Lowstep - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
199,190,Trek Dual Sport+ - 2018,Trek,Electric Bikes,2018,2799.99,2026-04-01 21:38:58.421075,DataLake
299,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
300,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake
301,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
302,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake
303,291,Electra Sweet Ride 1 (20-inch) - Girl's - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
304,292,Electra Sweet Ride 3i (20-inch) - Girls' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake
305,293,Electra Tiger Shark 1 (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,319.99,2026-04-01 21:38:58.421075,DataLake
306,294,Electra Tiger Shark 3i (20-inch) - Boys' - 2018,Electra,Children Bicycles,2018,369.99,2026-04-01 21:38:58.421075,DataLake

In [92]:

# If duplicates are same product but different model year → keep latest
df = df.sort_values('model_year', ascending=False) \
                   .drop_duplicates(subset=['product_id'], keep='first') \
                   .sort_values('product_id') \
                   .reset_index(drop=True)

In [93]:
duplicate_checks_Column(df,'product_id')

Duplicates in 'product_id': 0 (0.00%)
No duplicates found!

In [ ]:
duplicate_checks(df)

Total Rows       : 321
Duplicate Rows   : 0
Duplicate %      : 0.0%
No duplicates found!

In [102]:
negatives = df[df['list_price'] < 0]
print(f"Negative Prices    : {len(negatives)}")

Negative Prices    : 0

In [105]:
OUTPUT_DIR = r"D:\Ahmed\DataCarft_Material\Python-End-to-End-ETL-Pipeline-Project\Transformation\staging_1"
os.makedirs(OUTPUT_DIR, exist_ok=True)
df.to_csv(os.path.join(OUTPUT_DIR,'products.csv') , index=False)